version: '3'

services:
  api:
    container_name: api
    build: .
    volumes:
      - ..:/go/src/app:cached
    ports:
      - 8080:8080
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DSN: root:pass@tcp(db:3306)/dev?parseTime=true
    tty: true
    depends_on: 
      - db

  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dev
    tty: true
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/db

volumes: 
  db-data:

  